set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(RTS_ARM_TOOLCHAIN_BIN "" CACHE PATH
    "Directory containing the arm-none-eabi GCC executables")

if(RTS_ARM_TOOLCHAIN_BIN)
    list(PREPEND CMAKE_PROGRAM_PATH "${RTS_ARM_TOOLCHAIN_BIN}")
endif()

find_program(RTS_ARM_GCC NAMES arm-none-eabi-gcc REQUIRED)
find_program(RTS_ARM_AR NAMES arm-none-eabi-ar REQUIRED)
find_program(RTS_ARM_RANLIB NAMES arm-none-eabi-ranlib REQUIRED)
find_program(RTS_ARM_OBJCOPY NAMES arm-none-eabi-objcopy REQUIRED)
find_program(RTS_ARM_SIZE NAMES arm-none-eabi-size REQUIRED)

set(CMAKE_C_COMPILER "${RTS_ARM_GCC}" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER "${RTS_ARM_GCC}" CACHE FILEPATH "" FORCE)
set(CMAKE_AR "${RTS_ARM_AR}" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${RTS_ARM_RANLIB}" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCOPY "${RTS_ARM_OBJCOPY}" CACHE FILEPATH "" FORCE)
set(CMAKE_SIZE "${RTS_ARM_SIZE}" CACHE FILEPATH "" FORCE)

